# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: qgis/qgis

pipelines:
  branches:
    master, develop:
    - step:
          services:
            - docker
          caches:
            - docker
            - pip
            - qgisicons
          script: # Modify the commands below to build your repository.
            - python3 -m pip install -r requirements.txt
            - apt-get update
            - apt-get install -y wget
            - apt-get install -y unzip
            - QT_QPA_PLATFORM=offscreen
            - export QT_QPA_PLATFORM
            - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
            - echo "current dir:" $(pwd)
            - python3 --version
            - printenv PYTHONPATH
            - python3 -m pip install -r requirements.txt
            - wget https://bitbucket.org/jakimowb/qgispluginsupport/downloads/qgisresources.zip -O qgisresources.zip
            - unzip qgisresources.zip
            - python3 runfirst.py
            - python -m coverage run -m unittest discover -s tests
            #- /bin/bash runtests.sh


definitions:
  caches:
    qgisicons: qgisresources